name: Jekyll Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.1' # specify a compatible Ruby version here

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Deploy
        run: echo "Deploy step here" # replace with your actual deploy step
