name: Jekyll Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.1' # Updated to the latest stable version compatible with Jekyll

      - name: Install Bundler
        run: gem install bundler

      - name: Install Jekyll and dependencies
        run: bundle install

      - name: Verify Jekyll installation
        run: jekyll -v

      - name: Build Jekyll site
        run: bundle exec jekyll build --trace

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
